### ISSUE TITLE
Strange results using demo

### ISSUE THREAD

**Issue by fernandorovai** [tinyvision/SOLIDER-PersonSearch#4]
I downloaded the swin_tiny from SOLIDER and converted using convert_model.py script.
However, I'm getting strange results running the demo as : 
python demo.py --ckpt converted_swin_tiny.pth
Results:
![result-1](https://github.com/tinyvision/SOLIDER-PersonSearch/assets/3229701/2f06e802-bdfd-4598-89f1-356c9ac6c952)
![result-2](https://github.com/tinyvision/SOLIDER-PersonSearch/assets/3229701/bcbeddec-dde2-41e0-a708-b576d7fe4b14)
![result-3](https://github.com/tinyvision/SOLIDER-PersonSearch/assets/3229701/7a250a3d-d618-4c27-9048-0d0e9367da9f)
Any idea what is happening? Thanks

**Comment by fernandorovai** [comment]
Of course, that's because I did not train again for the specific task - thanks

**Comment by mirsaidl** [comment]
can you explain how you fix it 
i can not fix it

**Comment by AlecDusheck** [comment]
@fernandorovai @mirsaidl did you ever manage to find out why this was happening? Edit, figured it out, check issue 3
